# Generated by Django 5.0.1 on 2024-01-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('agirlik', models.FloatField()),
                ('kategori', models.CharField(max_length=100)),
                ('ucus_suresi', models.IntegerField()),
                ('menzil', models.IntegerField()),
                ('yuk_kapasitesi', models.FloatField()),
                ('navigasyon', models.BooleanField(default=False)),
                ('oto_pilot', models.BooleanField(default=False)),
                ('maksimum_hiz', models.FloatField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
