# Generated by Django 5.0.1 on 2024-01-31 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iha',
            name='kategori',
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('tanim', models.CharField(max_length=100)),
                ('iha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.iha')),
            ],
        ),
    ]
