# Generated by Django 5.0.1 on 2024-01-31 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_iha_kategori_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='iha',
        ),
        migrations.AddField(
            model_name='iha',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.kategori'),
        ),
    ]
