# Generated by Django 5.0.1 on 2024-02-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_kategori_iha_iha_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='navigasyon',
            field=models.CharField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='iha',
            name='oto_pilot',
            field=models.CharField(blank=True, default=False, null=True),
        ),
    ]
