# Generated by Django 5.0.1 on 2024-02-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_kiralanan_iha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiralanan_iha',
            name='baslangic_tarihi',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kiralanan_iha',
            name='bitis_tarihi',
            field=models.DateField(),
        ),
    ]
