# Generated by Django 5.0.1 on 2024-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_kiralanan_iha_baslangic_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiralanan_iha',
            name='baslangic_tarihi',
            field=models.DateField(),
        ),
    ]
