# Generated by Django 4.2.3 on 2024-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_kiralanan_iha_baslangic_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iha',
            name='eklenme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
