# Generated by Django 4.2.3 on 2024-02-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_iha_eklenme_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
